[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.dom", "php83Extensions.mbstring", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.pdo_sqlite", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.fileinfo", "php83Extensions.xml", "php83Extensions.bcmath", "php83Extensions.curl", "php83Extensions.intl", "php83Extensions.tokenizer", "nodejs_20", "npm-9_x"]

[phases.build]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-80}"
